package com.localdrop.diagnostics;

public enum DiagnosticEventType {
    DISCOVERY_STARTED,
    DISCOVERY_STOPPED,
    DISCOVERY_SEND_BROADCAST,
    DISCOVERY_SEND_UNICAST,
    DISCOVERY_RECEIVED,
    DISCOVERY_REJECTED,
    DISCOVERY_ERROR,
    DEVICE_ADDED,
    DEVICE_UPDATED,
    DEVICE_EXPIRED,
    DEVICE_NOT_READY,
    TRANSFER_SERVER_STARTED,
    TRANSFER_SERVER_STOPPED,
    TRANSFER_SERVER_ERROR,
    TRANSFER_CLIENT_CONNECTING,
    TRANSFER_CLIENT_CONNECTED,
    TRANSFER_CLIENT_ERROR,
    TRANSFER_FILE_STARTED,
    TRANSFER_FILE_ACKED,
    TRANSFER_FILE_FAILED,
    TRANSFER_CANCELLED
}
